name: Run JS tests
on:
  - push
  - pull_request
jobs:
  node:
    name: Node v${{ matrix.node }}
    runs-on: ubuntu-24.04-arm
    env:
      MSHOULD_FAST: "1"
    strategy:
      matrix:
        node: [18.20.5, 20.18.1, 22.13.0] # LTS on Jan 2025. Hardcoded is more secure
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
  bun:
    name: Bun
    runs-on: ubuntu-24.04-arm
    env:
      MSHOULD_FAST: "1"
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: oven-sh/setup-bun@4bc047ad259df6fc24a6c9b0f9a0cb08cf17fbe5 # v2.0.1
        with:
          bun-version: latest
      - run: bun install
      - run: bun run --if-present build
      - run: bun run --if-present test:bun
  deno:
    name: Deno
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: denoland/setup-deno@909cc5acb0fdd60627fb858598759246509fa755 # v2.0.2
        with:
          deno-version: v2.x
      - run: deno install
      - run: deno task build
      - run: deno task test:deno
  lint:
    name: Lint
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - run: npm install
      - run: npm run build --if-present
      - run: npm run lint --if-present
  coverage:
    name: Measure coverage on Node
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@1e31de5234b9f8995739874a8ce0492dc87873e2 # v4
      - uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          registry-url: "https://registry.npmjs.org"
          cache: npm
      - run: npm install
      - run: npm run build --if-present
      - run: npm run test:coverage
